### ISSUE TITLE
Daniel said ask for it: Changing Single Click to Double Click by default or at least option in the settings.

### ISSUE THREAD

**Issue by spirulin** [elementary/os#349] opened 2020-05-07 12:58 UTC
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Feature
**Is your feature request related to a problem? Please describe.**
This one is ridiculous, to be honest, and I don't see how someone would find this useful - single click.
It just makes it harder to use the OS.
And makes you feel like you are sitting on eggs every time you move the mouse scared that you may press something and break the eggs...
Again forcing people to you it the way you want without an option to use it the way they want.

**Describe the solution you'd like**
Changing to Double click by default because most people would prefer it over single click. OR at least a toggle in the setting to change it yourself.

**Existing work**
Elementary tweaks. Again adding someone's PPA can be dangerous when even in the App Center you are showing a warning window for Non-curated apps/programs. It doesn't make sense. But we are forced to install it if we want to use your OS.

**Additional context**
For reference: https://www.reddit.com/r/elementaryos/comments/gdbo1k/tried_using_elementary_as_intended_without_any/

**Comment by cassidyjames** [comment] 2020-05-11 21:13
Duplicate of https://github.com/elementary/files/issues/1319

**Closed by cassidyjames** 2020-05-11 21:13 UTC
