### ISSUE TITLE
source lists need to reference Ubuntu codename not Elementary codename

### ISSUE THREAD

**Issue by chinarut** [elementary/os#316] opened 2020-03-10 21:21 UTC
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Describe the bug
I am migrating [bug 1629646 on Launchpad filed in 2016](https://bugs.launchpad.net/elementaryos/+bug/1629646) that still remains an issue today.

this issue is also referred to in 2018: [AppCenter:#565](https://github.com/elementary/appcenter/issues/565) (currently closed)

"hera" needs to be replaced with "bionic" in the following 4 source lists:

/etc/apt/sources.list
/etc/apt/sources.list.d/elementary.list
/etc/apt/sources.list.d/patches.list
/etc/apt/sources.list.d/appcenter.list

I can only assume there needs to be some kind of [update to the] finalization script whenever a mainline Ubuntu release (ie. bionic) is integrated into the current release of Elementary OS.

### To Reproduce
1. install Elementary OS 5.1 (hera)
2. sudo apt update
3. See errors

### Expected behavior

no errors

## Platform Information

- [ ] I'm using the latest version from git that I've manually compiled
- [x] I'm using the latest released stable version

## Additional context

this impacts anyone attempting to follow our [Developer Guide](https://elementary.io/docs/code/getting-started#getting-started) as beginners will not be able to install the SDK out of the box until this issue is addressed (or fixed manually):
`apt install elementary-sdk`

EDIT: I would say this issue is **critical** as it does not allow new users of Elementary to receive security updates.   Once I updated my source lists, I received 30+ updates next I opened up AppCenter.

**Comment by cassidyjames** [comment] 2020-04-09 17:25
This is not widely reproducible, so let's not pretend it affects all users everywhere—we'd definitely hear if that was the case. I believe previous investigations have shown that there is a(n intermittent) issue in Ubiquity, the Ubuntu installer, which incorrectly replaces sources.list entries with the elementary codename instead of leaving the Ubuntu one as we've configured.

It's unclear why/when this happens or how widespread it is.

**Comment by glauschwuffel** [comment] 2020-05-03 07:28
Just for the record: I experienced it today while installing it on a MacBook Pro (built in 2011).

I consider it to be a critical error as well because the user can't install anything related to elementary.

**Comment by cassidyjames** [comment] 2020-05-05 18:13
@glauschwuffel thanks for reporting. If you could share, what region are you in, and what language did you choose when installing?

**Comment by glauschwuffel** [comment] 2020-05-06 10:48
@cassidyjames I'm physically located in Germany and chose German as the language.

**Comment by danrabbit** [comment] 2020-05-07 04:59
I’m inclined to close this since it’s a Ubiquity issue and won’t be reproducible in Odin where we’re using distinst and mirrors.txt

**Comment by glauschwuffel** [comment] 2020-05-07 08:03
I‘d be happy to reinstall on the same machine once Ubiquity is gone just to make sure ...

**Comment by chinarut** [comment] 2020-05-21 12:11
thank you @cassidyjames for pointing out my net was a bit too wide!

the extra data I can provide now is the issue didn’t occur when I installed eOS to a friend’s HP laptop last week that maybe is a few years old.

the issue was consistent during multiple installs to a mid-2007 Macbook 2,1 which unfortunately cannot be used as a test machine any more - it officially kicked the bucket (thus my hiatus restructuring my world...)

I won’t be as active as I was prior so it’s okay to close this issue if you are not able to reproduce the issue @glauschwuffel - thank you everyone for chiming in.

**Comment by glauschwuffel** [comment] 2020-05-22 07:43
@chinarut No, I wasn't able to reproduce it. Happy to close this as well.

**Closed** 2020-05-22 07:44 UTC
Labels: Status: Incomplete
