### ISSUE TITLE
Wifi request doesn't show

### ISSUE THREAD

**Issue by andreacocci95** [elementary/os#314] opened 2020-03-06 00:25 UTC
Hi, when I try to connect on a new wifi network by clicking on the top bar, I receive an error that say that I can't connect to the network because the network is protected by password encryption. I know the password but I can't insert this neither after the click neither when I go to settings -> network -> wirless. Can you help me?

**Comment by cassidyjames** [comment] 2020-03-06 00:37
@andreacocci95 have you installed the `backport-iwlwifi-dkms` driver in AppCenter? If so, try uninstalling that and restart your computer.

**Comment by andreacocci95** [comment] 2020-03-06 17:22
> @andreacocci95 have you installed the `backport-iwlwifi-dkms` driver in AppCenter? If so, try uninstalling that and restart your computer.

I tried with backport-iwlwifi-dkms and without it. Same problem. Is it just a my problem?

**Comment by davidmhewitt** [comment] 2021-02-22 10:19
This sounds like a duplicate of: https://github.com/elementary/wingpanel-indicator-network/issues/32 which has since been fixed, so I'll close this issue. Please open a new issue at https://github.com/elementary/wingpanel-indicator-network/issues if you are still experiencing this issue.

**Closed by davidmhewitt** 2021-02-22 10:19 UTC
