### ISSUE TITLE
App Store Searches Should Display App Sources And Versions

### ISSUE THREAD

**Issue by zach-hopkins** [elementary/os#382] opened 2020-07-08 07:29 UTC
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Feature

As you can see, the App Store search results can be confusing and unprofessional when searching for an app with uncurated sources. It is difficult to differentiate between the apps to make a decision

![Image of Yaktocat](https://i.imgur.com/6K4hgDi.png)

**Describe the solution you'd like**
Add repo source column and/or app version column (preferably and) so the end-user can make a more informed decision 
As an example:

OBS | Flathub.org | 1.0
OBS Studio | AppStore | 1.2

**Comment by cassidyjames** [comment] 2020-07-08 17:09
This repository is for the elementary OS build system and **not a catch-all for the OS itself**. Please do not file issues for the operating system itself or apps here, as they will be closed or need to be manually transferred.

If you are on elementary OS and trying to report an issue with something in the OS itself:

1. Open System Settigns → About → Report a Problem
2. Choose the appropriate category and component
3. Follow the prompts to report a problem

If you are not on elementary OS, please:

1. Visit https://github.com/elementary
2. Use your best effort to find the correct repository
3. Check for similar or duplicate issues to what you're trying to report
4. If none are found, file a new issue against that repository

---

That said, this looks like it is a duplicate of https://github.com/elementary/appcenter/issues/1140

**Closed by cassidyjames** 2020-07-08 17:09 UTC
