### ISSUE TITLE
I send my bugs and issues while work

### ISSUE THREAD

**Issue by nikolayval** [elementary/os#339] opened 2020-04-28 05:24 UTC
Hello! I'm Windows user in last 10 years. Now I'm first time trying Linux with Elementary OS. 

And I will to send you bugs and fixes while work. Sorry for bad English, I'm from Russia and still learning. 

I believe, if each user send to developers bugs, Elementary OS will be better! 

I attache .docx (Word-document). Please, send this bugs to developers. Thank you!

In future my work, I also will send bugs and issues report.

[Elementary OS issues.docx](https://github.com/elementary/os/files/4543486/Elementary.OS.issues.docx)

**Comment by ryonakano** [comment] 2020-04-28 05:57
Hello, thank you for your issue reports! I'm happy you get interested in elementary.

I have some suggestions for future reports:

- **Report your issue to the appropriate repository per problem.** We prepare repositories per components. For example, https://github.com/elementary/files if for the default file manager and https://github.com/elementary/gala is for the window manager. If you want to submit multiple issues you're facing, please submit a single issue report to the appropriate repository per issue. For example,

> Hotkey to create empty file. In File Manager I can create empty folder using Shift
\+ Ctrl + N buttons. It’s nice. But also I want hotkey to create empty files, I think it’s
simple and important.

This should be submitted at https://github.com/elementary/files.

Don't worry about posting your issue to a wrong repository, developers can transfer it to the appropriate place.

- **Check if your issue has already reported.** When you report your issue, you should check whether it's already reported or not. For example,

> Keyboard layout issues. I&#39;m live in Russia. My primary language is Russian. Also
sometimes I’m working with English. In my Elementary OS system installed 2
languages (Russian and English). The problem is that Elementary OS is very slowly
changing the keyboard layout. I press Shift + Alt buttons, then I see 1.5 second
delay, before keyboard layout was switched. Also I see, that from English lang to
russian keyboard layout switch faster, than from Russian to English. When I switch
language from Russian to English, I see delay (1.5 or 2 seconds maybe). For
example, in Windows keyboard layout switch instantly. Please, fix it!

This issue is already posted at elementary/gala#220.

When the issue you're trying to report is already reported, go to the issue page and do :+1: to the author's comment.

**Comment by ryonakano** [comment] 2020-04-28 06:13
> 2. Can’t see indicators in Top Panel.

This is intentional and we may not address this. Original issue is elementary/wingpanel#96. If you really want to show indicators, there is a community project that bring back them: https://github.com/donadigo/wingpanel-indicator-namarupa

> 4. Don’t work right click on Touchpad.

This seems to be a hardware-specific issue.

> 6. Issue with Fulscreen mode.

This is because the window manager moves the full-screened window to the new blank workspace. So, pressing `Super (Win)` + `←` should show your apps.

**Comment by danrabbit** [comment] 2020-04-29 14:48
I'm going to close this because as pointed out by @ryonakano group reports like this are untrackable. Please open individual reports for each separate issue

**Closed by danrabbit** 2020-04-29 14:48 UTC
