### ISSUE TITLE
FileZilla is not shown correctly and some functions cannot be done

### ISSUE THREAD

**Issue by carazo** [elementary/os#322] opened 2020-04-05 14:54 UTC
Hello,

Firstly, thanks for this distro. This is great and I am an user and also a fan.

I am having problems with FileZilla, it seems that for some reason this is not being well drawn, look at it:
![image](https://user-images.githubusercontent.com/2990568/78501860-10296180-775e-11ea-9c78-8ed76bdf465f.png)

How could I solve it? I have tried to install a recent version of FileZilla and it also happens (not only with the version in the repository).

I am using the latest version of your distro.

![image](https://user-images.githubusercontent.com/2990568/78501817-cc365c80-775d-11ea-8bb1-bee95ed4c750.png)

Thanks in advance.

**Comment by davidmhewitt** [comment] 2021-02-22 10:00
This appears to be a duplicate of: https://github.com/elementary/gala/issues/244

It has been resolved in the currently unreleased elementary OS 6.0

**Closed by davidmhewitt** 2021-02-22 10:00 UTC

**Comment by carazo** [comment] 2021-02-22 10:29
Perfect. Thanks for your words.

Waiting for elementaryOS 6 :)
