### ISSUE TITLE
Deactivating Laptop sreen not working when second screen is connected via USB-C

### ISSUE THREAD

**Issue by matthiasgomolka** [elementary/os#346] opened 2020-05-07 06:00 UTC
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Describe the bug
I have a notebook running elementary and a 27" screen connected via USB-C. Since the pixel density is very different on both screens I prefer to use only the 27" screen. Thus, I want to deactivate the notebook screen in the settings:

However, this has no effect and I need to close the notebook in order to switch off it's screen.

### To Reproduce
Steps to reproduce the behavior (assumend english names in parentheses):
1. Open the "Bildschirme" ("Screens") settings
2. Click on the 'gear' for individual screen settings
3. Deactivate "Diesen Bildschirm nutzen" ("Use this screen")
4. Click on "Übernehmen" ("Apply") and see that the notebook screen keeps activated.

### Expected behavior
The notebook screen should be switched off.

### Screenshots or screen recordings
![image](https://user-images.githubusercontent.com/6517388/81258949-1e0d2380-9037-11ea-8565-19403226bb11.png)

## Platform Information
![image](https://user-images.githubusercontent.com/6517388/81259553-7bee3b00-9038-11ea-8a5b-39fe04154677.png)

- [ ] I'm using the latest version from git that I've manually compiled
- [x] I'm using the latest released stable version

## Additional context
This works on pop!_os 20.04 (if this is of any help, assuming some related underlying code)

**Comment by davidmhewitt** [comment] 2021-02-22 11:12
This appears to be a duplicate of: https://github.com/elementary/switchboard-plug-display/issues/131

**Closed by davidmhewitt** 2021-02-22 11:12 UTC
