### ISSUE TITLE
ISO does not display video on AMD RX 6700XT

### ISSUE THREAD

**Issue by thatLeaflet** [elementary/os#634] opened 2022-11-02 22:56 UTC
ISO information: elementaryos-6.1-stable.20211218-RX.iso

OS information: 6.1 Jolnir, built on Ubuntu 20.04.3 LTS, Linux kernel 5.11.0-43 generic

When booting, nothing gets displayed after the initial "try or install ElementaryOS" screen.

In order to boot into the system, I need to add the nomodeset option.

My graphics card is an XFX Radeon 6700XT Qick 319 Black. My CPU is a Ryzen 5600x so it has no onboard graphics to fall back to.

I also tried booting with and without secure boot, no difference.

**Comment by peteruithoven** [comment] 2022-11-03 00:11
While elementary OS probably can't change the drivers included, since it's based on Ubuntu (where you'd face the same issue) the following feature should make your live easier: https://github.com/elementary/os/pull/627

**Comment by truefakts** [comment] 2024-02-17 22:50
This report is old and should be closed. The root cause is likely the really dated kernel 5.11.0-43 generic which does not support this graphics card. Elementary, and Ubuntu both have used newer kernels which support this graphics card for the passed year or so.

I have a 6600 XT which is essentially the same card, can confirm that kernels older than 6.2 do not work properly.

**Comment by lenemter** [comment] 2024-02-18 02:07
Closing because the issue is old. The newest elementary OS 7.1 uses kernel 6.5

**Closed by lenemter** 2024-02-18 02:07 UTC
