### ISSUE TITLE
'Sound' option in system settings causes said application to close

### ISSUE THREAD

**Issue by salperinlea** [elementary/os#372] opened 2020-06-30 01:12 UTC
## Prerequisites
- [X] I have searched open and closed issues for duplicates.

## Describe the bug
When one clicks on the 'Sound' icon under Hardware in system settings, system settings closes instantly.

### To Reproduce
1. Open System Settings
2. Click on the icon for Sound, in the Hardware section.
3. App closes.

### Expected behavior
One expects to be able to change the sound hardware in some way. This is impossible.

## Platform Information
![about](https://user-images.githubusercontent.com/40773827/86071451-3ef96000-ba4d-11ea-99d8-fa30daab55ea.png)

- [X] I'm using the latest released stable version

## Additional context
I have also noted that the pulseaudio installation in elementary seems to be faulty; one cannot use the pulseaudio equalizer at all, and sound is quite poor.
## Logs
checking syslog immediately after attempting to use the app shows that there's a segmentation fault:
`Jun 29 21:17:45 logos kernel: [37203.089181] io.elementary.s[22908]: segfault at 8 ip 00007f316c6bd102 sp 00007ffdb3dbc2d0 error 4 in libsound.so[7f316c6af000+1f000]`
`Jun 29 21:17:45 logos kernel: [37203.089185] Code: c5 08 48 8b 48 08 4c 8b 00 31 c0 e8 58 9c ff ff 49 39 ee 75 db 48 8b 83 88 01 00 00 48 8d 15 75 9d 00 00 be 80 00 00 00 31 ff <48> 8b 48 08 4c 8b 00 31 c0 e8 30 9c ff ff 49 8b 44 24 18 48 8b 78`

**Comment by cassidyjames** [comment] 2020-07-08 17:16
Thanks for filing an issue. However, this repository is for the elementary OS build system and **not a catch-all for the OS itself**. Please do not file issues for the operating system itself or apps here, as they will be closed or need to be manually transferred.

If you are on elementary OS and trying to report an issue with something in the OS itself:

1. Open System Settigns → About → Report a Problem
2. Choose the appropriate category and component
3. Follow the prompts to report a problem

If you are not on elementary OS, please:

1. Visit https://github.com/elementary
2. Use your best effort to find the correct repository
3. Check for similar or duplicate issues to what you're trying to report
4. If none are found, file a new issue against that repository

---

That said, it sounds like this is a duplicate of https://github.com/elementary/switchboard-plug-sound/issues/151

**Closed by cassidyjames** 2020-07-08 17:16 UTC
