### ISSUE TITLE
Video format support in Desktop ---> Wallpaper 

### ISSUE THREAD

**Issue by SethStormR** [elementary/os#376] opened 2020-07-03 14:40 UTC
This is for the wishlist. 
It would be awesome if elementary OS support videoclip as wallpaper. For now people have to turn to outdated thirdparty application to have live wallpaper on elementary OS.

Regards
Storm

**Comment by danrabbit** [comment] 2020-07-07 04:39
closing as a duplicate of https://github.com/elementary/switchboard-plug-pantheon-shell/issues/30

**Closed by danrabbit** 2020-07-07 04:39 UTC
