### ISSUE TITLE
MySQL Workbench 8 rendering issues, crashes

### ISSUE THREAD

**Issue by dominikzogg** [elementary/os#132] opened 2018-10-21 08:51 UTC
I would like to use MySQL Workbench 8 on elementary OS 5 (mysql-workbench-community_8.0.12-1ubuntu18.04_amd64.deb) from https://dev.mysql.com/downloads/workbench/.

Installation works fine. Start the application works fine, but adding a connection starts with rendering issues and save it crashes (most of the time) Connection to a database is not possible.

As far as I know this works on Ubuntu 18.04 without problems.

The 6.x version coming from the Ubuntu Mirrors works.

**Comment by dominikzogg** [comment] 2018-10-22 06:53
Seems to have the same error on play on linux https://plus.google.com/113574088919549111367/posts/BZiVGp4rHy7

**Comment by JMoerman** [comment] 2018-10-30 10:14
Rendering issues also occur with dialogs in the eclipse IDE (2018-09 version), on Loki this would also happen to the main windows and it would often crash X.org on starting the IDE.
![screenshot](https://user-images.githubusercontent.com/11899523/47710965-5f4b9880-dc34-11e8-8039-3c4c741bdb47.png)

**Comment by JMoerman** [comment] 2018-10-30 10:17
This seems to be a duplicate of https://github.com/elementary/gala/issues/244

**Comment by davidmhewitt** [comment] 2021-02-22 10:21
Indeed, it's a duplicate of the gala issue, closing.

**Closed by davidmhewitt** 2021-02-22 10:21 UTC
