### ISSUE TITLE
Multitasking view only works in main monitor

### ISSUE THREAD

**Issue by fsarrias** [elementary/os#291] opened 2020-01-24 17:42 UTC
Hello
When connecting more than one monitor to the system the multitasking view appears only in the main monitor, the other monitors connected remain with the current window without the possibility to open more workspaces there.
Best

## Prerequisites
- [ ] I have searched open and closed issues for duplicates.

## Feature
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Existing work**

**Describe alternatives you've considered**

**Additional context**

**Comment by cassidyjames** [comment] 2020-01-24 17:46
Thanks for reporting. This repo is for the OS build scripts. Closing as a duplicate of https://github.com/elementary/gala/issues/26 regardless.

**Closed by cassidyjames** 2020-01-24 17:46 UTC

**Comment by fsarrias** [comment] 2020-01-24 19:26
Oh sorry for the confusion, I will follow the original issue then
