### ISSUE TITLE
Application menu - Calculator - no focus

### ISSUE THREAD

**Issue by ruphu5** [elementary/os#169] opened 2019-01-24 09:41 UTC
I do not find a related topic, so I start a new one. 

I often use the hotkey for the application menu and type in "calc"(in german "rechner") to quickly access the calculator app. But when I hit enter to start the app, the new window is not focused, so that I need to Alt+Tab or click into it. That is very uncomfortable.

Please consider to have a look into that issue and to correct it. Right now I can only confirm that issue happens to the calculator app. 

With kind regards

**Comment by peteruithoven** [comment] 2019-01-24 10:00
@ruphu5 thanks for reporting. 

I'm afraid I see some overlap with:
https://github.com/elementary/applications-menu/issues/105
https://github.com/elementary/applications-menu/issues/19
https://github.com/elementary/gala/issues/1

Similar issues with other apps:
https://github.com/elementary/terminal/issues/66
https://github.com/elementary/mail/issues/215
https://github.com/elementary/mail/issues/156

I'm not sure whether this is a Gala (window manager) or Calculator specific issue. 

But I also can't reproduce your issue, see:
![screen record from 2019-01-24 10 56 36](https://user-images.githubusercontent.com/523210/51670520-156e1680-1fc7-11e9-84b3-7f895b6f8227.gif)

Could you include a screen recording? I can recommend [Screen Recorder](https://appcenter.elementary.io/com.github.mohelm97.screenrecorder).

**Comment by ruphu5** [comment] 2019-01-24 17:51
Hello peter,
yes you are right, those issues look just like what I mentioned here.
Btw: Yes, I am on Juno.

![screen record from 2019-01-24 18 42 05](https://user-images.githubusercontent.com/25183181/51697799-ff814580-2008-11e9-9f2b-b4f6ad18b88a.gif)

**Comment by peteruithoven** [comment] 2019-01-24 21:36
I'm closing this one in favor of: https://github.com/elementary/applications-menu/issues/19

**Closed** 2019-01-24 22:10 UTC
