### ISSUE TITLE
Screen Rotation 

### ISSUE THREAD

**Issue by wamari** [elementary/os#362] opened 2020-06-05 22:55 UTC
I have an HP Probook 430 G6 with touchscreen, sometimes when moving the laptop around especially when moving from my desk to somewhere else the screen rotates. It would be nice to have a screen rotation lock toggle.

**Comment by cassidyjames** [comment] 2020-07-08 17:23
Thanks for filing an issue. However, this repository is for the elementary OS build system and **not a catch-all for the OS itself**. Please do not file issues for the operating system itself or apps here, as they will be closed or need to be manually transferred.

If you are on elementary OS and trying to report an issue with something in the OS itself:

1. Open System Settigns → About → Report a Problem
2. Choose the appropriate category and component
3. Follow the prompts to report a problem

If you are not on elementary OS, please:

1. Visit https://github.com/elementary
2. Use your best effort to find the correct repository
3. Check for similar or duplicate issues to what you're trying to report
4. If none are found, file a new issue against that repository

---

That said, it sounds like this is a duplicate of https://github.com/elementary/switchboard-plug-display/issues/116

**Closed by cassidyjames** 2020-07-08 17:23 UTC
