### ISSUE TITLE
Fn media keys issue

### ISSUE THREAD

**Issue by luckydays** [elementary/os#198] opened 2019-05-06 10:29 UTC
Hey guys,

Thanks for all the amazing work you keep putting into ElementaryOS evolvement. It apparently becomes better and better monthly!

Could you assist me with this request, please?
Somehow I'm facing with the same issue, even after the latest updates.

After some period of listening to music through a multimedia player (mostly meaning here either Spotify, or Clementine, or [Harmony](https://getharmony.xyz/)), my Fn media keys just stop working at all. I mean Fn+Play/Fn+Pause, Fn+Next track, Fn+Previous track, Fn+Stop.
However, Fn+Vol Up and Fn+Vol Down keep working just fine.

This can occur both after some hours of work within a particular user session and after the second or third time when the computer went into a sleeping mode.
And importantly enough - I'm of course checking whether any other multimedia app is running in the background or not (through the System Monitor app).

What could you advise on this?

Looking forward to your reply.

Best wishes!

**Comment by peteruithoven** [comment] 2019-05-06 12:40
This might be a duplicate of: https://github.com/elementary/gala/issues/518

**Comment by peteruithoven** [comment] 2019-05-06 13:08
I just now understand you're issue is that they stop working after while. Which makes this actually a duplicate of: https://github.com/elementary/gala/issues/193

**Closed by peteruithoven** 2019-05-06 13:08 UTC
