### ISSUE TITLE
Dark theme (mode, variant) doesn't work in settings app

### ISSUE THREAD

**Issue by KohutYan** [elementary/os#358] opened 2020-05-22 13:13 UTC
After one of the updates dark mode stopped working in system settings application

**Comment by ryonakano** [comment] 2020-05-22 13:16
Closing as a duplicate of elementary/switchboard#156

**Closed by ryonakano** 2020-05-22 13:16 UTC

**Comment by ryonakano** [comment] 2020-05-22 13:25
elementary OS does not support dark style officially at the moment (so I guess you use elementary Tweaks which is unofficial), but it will be officially supported in the next version of elementary OS. The way to enable dark variant is different between the new official one and the current one (how Tweaks does), and this causes the "issue" you reported. It depends on its developers if an app respects elementary OS-wide dark preference (like the dark mode in iOS), but System Settings is ready for this so it should be displayed in dark style if you choose on the next version of elementary OS.
