### ISSUE TITLE
Long freeze when changing screen brightness with Fn keys (Dell Inspiron 5458)

### ISSUE THREAD

**Issue by o-alquimista** [elementary/os#139] opened 2018-10-25 19:54 UTC
There is a long UI freeze when I increase/decrease the screen brightness of this laptop with the Fn + <brightnessUP/brightnessDown> keys. The cursor still moves, but menus from the panel won't open, right click context menus won't open, further pressing of Fn+anything will not cause any feedback or change for the duration of this "cooldown", after which everything starts working again.

So, in short, when I change screen brightness with the keyboard shortcuts, some part of the UI experience locks up. It may last for minutes until it resumes normal operation.

**Comment by peteruithoven** [comment] 2018-10-25 20:06
Thanks for the report! This looks like a duplicate of https://github.com/elementary/wingpanel-indicator-power/issues/92

**Closed by peteruithoven** 2018-10-25 20:06 UTC
Labels: Status: Duplicate
