### ISSUE TITLE
GRUB cannot be hidden - (I have a workaround!)

### ISSUE THREAD

**Issue by Khayasen** [elementary/os#666] opened 2023-05-26 02:33 UTC
I did a fresh install for Elementary OS (compelete wipe - recommended partition). But when I boot up, the GRUB shows and makes me wait 30 seconds to boot into eOS (which can be bypassed by pressing enter).

Last night, I did some research and stumbled across a post in askubuntu ([https://askubuntu.com/questions/1236136/ubuntu-20-04-lts-cant-hide-grub-menu](url)).  What I did from the website are as such:

Adding 
`GRUB_RECORDFAIL_TIMEOUT=0` to `/etc/default/grub` via `sudo nvim /etc/default/grub`
and
`GRUB_HIDDEN_TIMEOUT_QUIET=true` to `/etc/default/grub` via `sudo nvim /etc/default/grub`
and finishes with `sudo update-grub`. The issue fixed! 

So I think the reason why this happen is because eOS defaults to LVM partition on the root, which GRUB cannot access (as said in the article I provided).

**Comment by ryonakano** [comment] 2024-09-15 00:36
Closing as duplicate of https://github.com/elementary/triage/issues/109

**Closed by ryonakano** 2024-09-15 00:36 UTC
