### ISSUE TITLE
Bluetooth should remember previous setting. 

### ISSUE THREAD

**Issue by marcocadete** [elementary/os#381] opened 2020-07-07 13:55 UTC
### Bluetooth keeps turning on when I login

_Not sure if this is a bug or how it's designed to work._

When I disable the bluetooth and restart my computer, it turns back on automatically.
It would be nice to either have it off by default or remember/persist the previous setting.

My Laptop Specs:
- Elementary OS 5.1.6 Hera x86_64
- Kernel 5.3.0-62-generic
- CPU: Intel i7-7700HQ (8) @ 2.800GHz
- GPU: NVIDIA GeForce GTX 1050 Mobile
- RAM: 8GB

**Comment by marcocadete** [comment] 2020-07-07 16:10
Just noticed that the Bluetooth enables itself. Not sure what triggered it. I had it disabled and when I looked at it again after a while, I noticed that it had switched itself on.

**Comment by marcocadete** [comment] 2020-07-07 18:05
Also, when the Bluetooth is disabled and I lock the screen with the windows key + L, it enables the Bluetooth automatically. I'm constantly having to check if Bluetooth is enabled.

**Comment by cassidyjames** [comment] 2020-07-08 17:14
Thanks for filing an issue. However, this repository is for the elementary OS build system and **not a catch-all for the OS itself**. Please do not file issues for the operating system itself or apps here, as they will be closed or need to be manually transferred.

If you are on elementary OS and trying to report an issue with something in the OS itself:

1. Open System Settigns → About → Report a Problem
2. Choose the appropriate category and component
3. Follow the prompts to report a problem

If you are not on elementary OS, please:

1. Visit https://github.com/elementary
2. Use your best effort to find the correct repository
3. Check for similar or duplicate issues to what you're trying to report
4. If none are found, file a new issue against that repository

---

That said, it sounds like this is a duplicate of https://github.com/elementary/wingpanel-indicator-bluetooth/issues/117

**Closed by cassidyjames** 2020-07-08 17:14 UTC

**Comment by marcocadete** [comment] 2020-07-08 20:48
Okay, thanks for your feedback. Noted.
