### ISSUE TITLE
Elementary OS Gestures

### ISSUE THREAD

**Issue by SephReed** [elementary/os#342] opened 2020-05-05 17:34 UTC
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Feature
**Is your feature request related to a problem? Please describe.**

Spoiled by MacOS, switching between workspaces, opening launcher, and viewing all screens are gestures I've gotten dependent on for getting around.

**Describe the solution you'd like**

What MacOS does works, but honestly anything which makes gestures more accessible would do.
<img width="639" alt="Screen Shot 2020-05-05 at 12 29 15 PM" src="https://user-images.githubusercontent.com/14002040/81096500-13824b00-8ecc-11ea-9df1-bc83ab3ba5e2.png">

**Existing work**

There are plenty of links on [how to do this in Elementary](https://duckduckgo.com/?q=gestures+in+elementary+os&t=brave&ia=web).  If I remember correctly, the big blocker was having to do a major switch somewhere to support it.

**Describe alternatives you've considered**

I could become one of those people who never takes their hands off the keyboard.

**Additional context**

I know this has been asked somewhere else, but I couldn't find it.  I really just made this issue so I can look it up every 6 months or so when checking to see if Elementary has that one last pivotal feature I'm waiting for.

**Comment by danrabbit** [comment] 2020-05-05 17:45
Closing as a duplicate of https://github.com/elementary/switchboard-plug-mouse-touchpad/issues/16

**Closed by danrabbit** 2020-05-05 17:45 UTC

**Comment by SephReed** [comment] 2020-05-05 17:47
Thank you.  That was the one I was searching for.
