### ISSUE TITLE
"Network disconnected" notification spam

### ISSUE THREAD

**Issue by OrkanSaklan** [elementary/os#269] opened 2019-12-16 17:35 UTC
## Prerequisites
- [ y ] I have searched open and closed issues for duplicates.

## Describe the bug
Very often I get spammed that the Network Connection is disconnected. It doesn't matter if I'm connected or not. It doesn't even matter if Wi-Fi is enabled or not. The only way to get rid of the non-sense notifications is to end the process of nm-applet. In other words, if I have a stable internet connection via Wi-Fi nm-applets spams me that the internet connection is lost, even it's still there.

### To Reproduce
Sometimes it spams, sometimes it behaives, I'm not really sure what causes it this malfunction.

### Screenshots or screen recordings
![nm-applet-notification-spam](https://user-images.githubusercontent.com/16062633/70927163-c988ed80-202e-11ea-80a8-c444741a7489.png)

## Platform Information
![Screenshot von 2019-12-16 18 12 43](https://user-images.githubusercontent.com/16062633/70927676-b7f41580-202f-11ea-91dc-ed0d90761571.png)

**Comment by danrabbit** [comment] 2019-12-17 19:06
Gonna close this as a duplicate of https://github.com/elementary/default-settings/issues/145

**Closed by danrabbit** 2019-12-17 19:06 UTC

**Comment by cassidyjames** [comment] 2019-12-17 19:08
@OrkanSaklan it looks like you have added an unsupported tray implementation of some sort, did this start after that? I've heard of a duplicate networking applet when that's done, and I wonder if this is related.

**Comment by OrkanSaklan** [comment] 2019-12-18 13:22
> @OrkanSaklan it looks like you have added an unsupported tray implementation of some sort, did this start after that? I've heard of a duplicate networking applet when that's done, and I wonder if this is related.
> 
> Edit: Ah yeah the notifications themselves are too spammy anyway, and fixing [elementary/default-settings#145](https://github.com/elementary/default-settings/issues/145) would also fix this.

I have installed indicator-application & wingpanel-indicator-ayatana since day 1, eOS Juno is out. That wasn't an issue back then. Everything just became buggy after eOS updates.

**Comment by OrkanSaklan** [comment] 2019-12-18 13:23
> Gonna close this as a duplicate of [elementary/default-settings#145](https://github.com/elementary/default-settings/issues/145)

Sry, I missed that issue!

**Comment by mcclurgm** [comment] 2020-03-22 23:06
I think this is a separate issue from elementary/default-settings#145, if I understand the bug here. I regularly get spammed with notifications when my laptop goes to sleep. When I wake it back up and log in, I get one (or often many) notifications that my connection has been lost. I haven't been able to track down when that happens, but I do know that it's a different behavior.
