### ISSUE TITLE
Irregularly shaped help button (?)

### ISSUE THREAD

**Issue by gmikhail** [elementary/os#165] opened 2019-01-04 16:15 UTC
I may be wrong, but it seems to me that the help button in the “About system” tab is irregularly shaped. It should be either a circle or the usual rectangular button labeled "Help" or something like that.

![2019-01-03 174524](https://user-images.githubusercontent.com/4838367/50698055-9aab7e80-104c-11e9-96c0-28f8380159ed.png)

**Comment by peteruithoven** [comment] 2019-01-04 16:33
Thanks for the report! I'm afraid this is a duplicate of https://github.com/elementary/switchboard-plug-about/issues/55

This is also the wrong repository to post the issue to. You can use the *Report a Problem* button in the About settings to help you locate the right repo.

**Closed by peteruithoven** 2019-01-04 16:33 UTC
Labels: Status: Duplicate
