### ISSUE TITLE
Toggle full screen with f11 freezes desktop

### ISSUE THREAD

**Issue by n8x0b7T** [elementary/os#309] opened 2020-03-03 18:11 UTC
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Describe the bug
When using f11 to toggle full screen, the entire desktop besides the mouse froze up. Normally it wouldn't be an issue, but when you hold down f11 for more than about a second it begins to toggle full screen multiple times causing the entire desktop to freeze. I waited for about 5 minutes and it didn't respond until I forced a restart.

### To Reproduce
Steps to reproduce the behaviour:
I did this on Firefox, but I would imagine the same thing happens for other applications.
1. Focus a window in the foreground
2. Hold down the f11 key for about a second

### Expected behaviour
The team should consider making the f11 key only trigger the toggle on keypress up. Currently it is probably using if key pressed which causes the toggle to happen dozens if not hundreds of times.

## Platform Information
![About](https://user-images.githubusercontent.com/25648252/75805221-6e25ec00-5d4f-11ea-9fc2-8c852383cb6c.png)

Please check what applies:
- [ ] I'm using the latest version from git that I've manually compiled
- [x] I'm using the latest released stable version

**Comment by cassidyjames** [comment] 2020-03-10 17:40
I can't reproduce this here. Is it only happening in certain apps?

**Comment by JandJ101** [comment] 2020-03-13 22:11
It happened in firefox for me. It may be that my laptop isn't the best. But, it would still be nice to make it only maximize once when you hold down the button, instead of toggling back and forth.

**Comment by cassidyjames** [comment] 2020-04-21 22:43
Oh, I hear the issue now. I *think* that is internal to Firefox, as we don't actually implement a system-wide F11 fullscreen shortcut.

**Comment by davidmhewitt** [comment] 2021-02-22 11:17
Closing as this sounds like a firefox issue. Please open a new issue in the https://github.com/elementary/gala repo if you experience this with elementary's fullscreen functionality instead of just Firefox's.

**Closed by davidmhewitt** 2021-02-22 11:17 UTC
Labels: Status: Incomplete
