### ISSUE TITLE
UEFI boot manager display label should be "Elementary" instead of "ubuntu"

### ISSUE THREAD

**Issue by eljefuri** [elementary/os#151] opened 2018-11-08 11:08 UTC
The default UEFI label for Elementary is "ubuntu". Especially on systems where other Ubuntu-based installations are present, this creates confusion. I can manually rename it with: `efibootmgr -b 0000 -B` and then `efibootmgr -c -L "Elementary"`

**Comment by eljefuri** [comment] 2018-11-08 19:10
What is involved in getting one's own secure boot key?

**Comment by lhorace** [comment] 2019-03-15 22:28
> The default UEFI label for Elementary is "ubuntu". Especially on systems where other Ubuntu-based installations are present, this creates confusion.

Exactly, I came across the same problem here.

> What is involved in getting one's own secure boot key?

I suspect, requires Microsoft signing them by their own chain, though, I thought there was alternatives for Open Source projects?  In any case, in some situations (don't have statistics), it's possible for us to import our own UEFI keys into UEFI BIOS.

**Comment by MycroftHolmes1989** [comment] 2019-09-11 17:18
The problem is, it makes dual-booting with Ubuntu from a single disk well-nigh impossible without Ubuntu's EFI entry getting overwritten, since it overwrites Ubuntu folder in EFI partition.

**Comment by cassidyjames** [comment] 2019-09-11 19:03
@eljefuri as far as I understand, contacting Microsoft and convincing them to sign your kernel image, and then waiting for them to sign each kernel update. :grimacing:

**Comment by davidmhewitt** [comment] 2021-02-22 10:52
This should be resolved in elementary OS 6.0. The new installer uses `efibootmgr` to set a more descriptive label on the EFI entry.

**Closed by davidmhewitt** 2021-02-22 10:52 UTC
