### ISSUE TITLE
Screenshot to clipboard

### ISSUE THREAD

**Issue by Sonny812** [elementary/os#184] opened 2019-03-01 11:59 UTC
Can't copy screenshots to clipboard with keyboard shortcuts. Whole screen, current window and selected area not working as well.

**Comment by peteruithoven** [comment] 2019-03-01 12:24
Thanks for the report! I'm afraid this is a duplicate of https://github.com/elementary/gala/issues/474

**Closed by peteruithoven** 2019-03-01 12:24 UTC
