### ISSUE TITLE
Russian installation hang on 35%

### ISSUE THREAD

**Issue by eldrfoa** [elementary/os#626] opened 2022-09-25 10:32 UTC
https://elementaryos.stackexchange.com/questions/28751/why-does-elementary-os-installation-hang-at-35
https://elementaryos.stackexchange.com/questions/28242/odin-installation-stuck-at-70
Still present after a year

**Comment by jeremypw** [comment] 2022-09-25 10:47
If it is related to a single locale then it suggests a mistranslation that omits a placeholder or something?  Has a Russian speaker checked the po file for the installer?

**Comment by davidmhewitt** [comment] 2022-09-26 17:17
This is a duplicate of https://github.com/elementary/installer/issues/591

**Closed by davidmhewitt** 2022-09-26 17:17 UTC
Labels: Status: Duplicate
