### ISSUE TITLE
Mutter causes weird artifacts/ghost windowborders

### ISSUE THREAD

**Issue by J0Ar** [elementary/os#214] opened 2019-07-15 00:44 UTC
elementaryOS has some strange visual glitches since some time now…1 or 2 months i think.
Look at the [Video](https://streamable.com/stu1m)
So far these are visible in Firefox and Synaptic's context menus.

System:![Bildschirmfoto von 2019-07-15 02-22-59](https://user-images.githubusercontent.com/23266409/61191188-7f7a9500-a6a7-11e9-9b45-2f804d36fa71.png)

I think this has something to do with Mutter…i tried the LiveSystem with the older packages…
- Boot USB 'elementaryos-5.0-stable.20181016.iso'
- changed resolution from 1920x1080 to 1600x900 as normal and activated WLAN
- disabled the Repo 'dep cdrom:…'  with 'sudo nano /etc/apt/sources.list'
- 'sudo apt update && sudo apt install firefox'
- used my own firefox user profil because the bookmarks toolbar is more full^^
- **Result: Everything is fine**

Then:
- installed/update to the newest mutter package 'sudo apt install libmutter-2-0' (+ dependencies)
- logged out…in
- **Result: Artifacts/ghost window borders are visible**

So i think this has nothing to do with odd drivers or kernels…or am i wrong?

**Comment by J0Ar** [comment] 2019-07-15 21:54
Ok i have some news…i have tried another machine (Laptop) with intel graphics. Same issue.
- System and mutter files before update…
![System before update](https://user-images.githubusercontent.com/23266409/61251451-cf666400-a75a-11e9-9e04-a47f2fe5c746.png)
- I have done the update with `sudo apt install libmutter-2-0`
![Mutter update](https://user-images.githubusercontent.com/23266409/61251461-d2615480-a75a-11e9-9892-3f6834a44c37.png)

- Some videos…unfortunately, this only works externally with a smartphone. Using Screenrecorder did not work…the artifacts are not visible when the recording is active. 

[Firefox](https://streamable.com/yji1v)

[Synaptic](https://streamable.com/p74jt)

**Comment by danrabbit** [comment] 2020-01-30 23:24
Closing as a duplicate of https://github.com/elementary/os-patches/issues/80

**Closed by danrabbit** 2020-01-30 23:24 UTC
