### ISSUE TITLE
Videos freeze while audio continues to play in Chrome, Videos, etc. [$10]

### ISSUE THREAD

**Issue by cassidyjames** [elementary/os#121] opened 2018-10-05 16:26 UTC
_From @pbirkbeck on July 9, 2018 4:1_

On elementary OS Juno beta videos freeze while watching netflix, youtube etc. Audio continues to play. When I move the mouse around the video resumes playing but freezes a few seconds later without any mouse movement.

**Comment by kubaplas** [comment] 2018-10-09 16:49
I have the same issue on 6th gen Intel laptop with Youtube on Chrome browser.
4.15.0-36-generic kernel

**Comment by PNunesDev** [comment] 2018-10-17 20:02
I can also confirm that this also happens to me on youtube or any video.
i5 4200u with Intel HD.
Elementary OS Juno 0.5
Kernel: 4.15.0-36-generic 

I've started to use Linux recently, but I'm aware Elementary don't usually push kernel updates.
so, this is issue is going to stay in here for the rest of the 2 years of the 0.5 version, or will I need to force a kernel update just like the PRO linux users :P?

**Comment by cassidyjames** [comment] 2018-10-17 22:21
@PNunesDev elementary OS uses the Ubuntu kernel, which gets frequent updates gets upgraded to newer versions along with the rolling "HWE" stack.

**Comment by otavioschwanck** [comment] 2018-10-18 14:43
Confirm here too.

![image](https://user-images.githubusercontent.com/9551316/47162749-f3c80980-d2ca-11e8-8c30-f99b5ba29150.png)

**Comment by Victor-Arruda** [comment] 2018-10-18 14:45
Same issue here too.

**Comment by azhar25git** [comment] 2018-10-18 16:55
Same here on core-i7 3rd gen...

**Comment by otavioschwanck** [comment] 2018-10-18 18:37
Update:
If you keep moving the mouse, the video don't freeze.  Only happens when mouse is stopped.

**Comment by kubaplas** [comment] 2018-10-18 18:48
I've updated the kernel to 4.18.15, didn't help.

**Comment by jorge-aparicio** [comment] 2018-10-18 19:01
I tried updating to the latest mesa drivers also didn't help

**Comment by PNunesDev** [comment] 2018-10-18 19:53
> I've updated the kernel to 4.18.15, didn't help.

Well, that's not good, probably the issue is related with intel mesa drivers.
Does intel contain any easy update system for their GPU drivers?

**Comment by otavioschwanck** [comment] 2018-10-18 20:00
I have ubuntu 18.04 and mint 19 (same base, kernel and drivers), and this issue occurs.

**Comment by leonidasv** [comment] 2018-10-18 20:37
Core 7th gen, HD graphics 620 here, same issue. 

Tried upgrading to kernel 4.18.0 and 4.18.15 but this same issue continues haunting me.

I think it's not a driver problem, but Gala's compositor one. I've never had this issue using Gnome.

For example:
I managed to make a video stop freezing by holding a Terminal window in front of it, with the beam animation. While the animation was playing, the video on the browser played smoothly. But, once the beam animation stopped (it automatically pauses after some seconds), almost instantly, the video froze. 

I think it's related to the Gala screen refresh rate. If there's no event coming from the system UI to force it redraw the screen every 1/60 second (in a 60hz display) for quite some time, it freezes and await for the next system event forcing it to redraw. This looks like a trick to save power, but this side-effect is annoying. 

I opened an issue on Gala repo: elementary/gala#368

**Comment by jorge-aparicio** [comment] 2018-10-18 21:35
Update videos play perfectly for some reason in firefox not sure what makes it different but its a temporary solution for online video at least

**Comment by otavioschwanck** [comment] 2018-10-18 22:53
Confirmed:  On firefox, all works well.

**Comment by touchwood99** [comment] 2018-10-19 20:19
Issue exists for me in Firefox - not in Chromium. 
When selecting full screen in Youtube, display freezes. Audio continues playing.
Escape key has the screen flashing.
Its as though the GPU is not being used.

**Comment by MichelFrade** [comment] 2018-10-19 21:34
Same issue here too.
![captura de tela de 2018-10-19 18-34-16](https://user-images.githubusercontent.com/16271692/47244898-9c5e9200-d3cd-11e8-9045-39c9252775ce.png)

**Comment by cassidyjames** [comment] 2018-10-19 21:36
Marking as high priority since this affects a lot of people and we're getting a lot of duplicate reports of it across issue trackers and social media. Also, it really does make it difficult to do anything video related in a variety of apps across a variety of hardware.

I suppose a next step would be to see if this also happens on other OSes with the same hardware stack, like Ubuntu 18.04. Hopefully we can narrow down where the issue is.

**Comment by otavioschwanck** [comment] 2018-10-19 22:39
> Marking as high priority since this affects a lot of people and we're getting a lot of duplicate reports of it across issue trackers and social media. Also, it really does make it difficult to do anything video related in a variety of apps across a variety of hardware.
> 
> I suppose a next step would be to see if this also happens on other OSes with the same hardware stack, like Ubuntu 18.04. Hopefully we can narrow down where the issue is.

Have ubuntu 18.04 and Mint 19 here, dont happen.  Same Drivers.

**Comment by Victor-Arruda** [comment] 2018-10-19 22:44
> Marking as high priority since this affects a lot of people and we're getting a lot of duplicate reports of it across issue trackers and social media. Also, it really does make it difficult to do anything video related in a variety of apps across a variety of hardware.
> 
> I suppose a next step would be to see if this also happens on other OSes with the same hardware stack, like Ubuntu 18.04. Hopefully we can narrow down where the issue is.

Have Mint 19 in another partition here, works fine.

**Comment by yarbsemaj** [comment] 2018-10-20 19:38
Same here will all the same issue and fixes tried with Intel GMA 620

**Comment by ritikchanna** [comment] 2018-10-21 12:55
Quick fix for Chrome users, disable H/W acceleration in settings.

For Developers, I faced the same issue on Loki when I installed open source drivers for my amd gpu. Might not be related but might help you narrow it down.

**Comment by leonidasv** [comment] 2018-10-21 16:50
> I suppose a next step would be to see if this also happens on other OSes with the same hardware stack, like Ubuntu 18.04. Hopefully we can narrow down where the issue is.

Arch Linux + Gnome w/ Intel drivers on X11 has no issue playing videos on Chrome on my hardware. I first thought it was a kernel/driver issue, but upgrading elementary to 4.18 did not solve.

**Comment by touchwood99** [comment] 2018-10-21 20:04
Today - Clean install of Ubuntu 18.10 on same PC running Juno There are no issues with video playback in YouTube.

**Comment by yarbsemaj** [comment] 2018-10-21 20:18
> Today - Clean install of Ubuntu 18.10 on same PC running Juno There are no issues with video playback in YouTube.

Had the same experience today, it's a shame really

**Comment by otavioschwanck** [comment] 2018-10-21 21:31
Franz have same problem, disabling hardware acceleration fix it.  Maybe it was related to Electron Apps vs Gala =D

**Comment by peteruithoven** [comment] 2018-10-21 21:58
Please people, use the thumbs up if you're not adding anything useful. There are many people who are receiving all sorts of notifications with every comment you post here.

**Comment by jorge-aparicio** [comment] 2018-10-22 07:55
@otavioschwank did you just disable it for the browser or is there a way to disable Hardware acceleration at an OS level?

**Comment by otavioschwanck** [comment] 2018-10-22 13:33
> @otavioschwank did you just disable it for the browser or is there a way to disable Hardware acceleration at an OS level?

just disable on browser and franz.  After disabling, no bugs happens.

**Comment by rkoesters** [comment] 2018-10-23 13:37
I was able to fix this on my machine (Intel HD Graphics 5500) by creating the file `/etc/X11/xorg.conf.d/20-intel.conf` with the contents:
```
Section "Device"
  Identifier  "Intel Graphics"
  Driver      "intel"
  Option      "TearFree"    "true"
EndSection
```

**Comment by kubaplas** [comment] 2018-10-23 15:52
I confirm, @rkoesters' solution fixed issue on my "HD Graphics 520 (rev 07)".

**Comment by Djaler** [comment] 2018-10-23 17:32
@cassidyjames can we include this file by default? Or maybe somehow by detecting intel graphics

**Comment by Djaler** [comment] 2018-10-23 18:19
Hmm, still not ideal solution. After creating this file I was faced with glitches in Chrome

**Comment by cassidyjames** [comment] 2018-10-23 19:39
After setting TearFree on my Intel i5-8300H, I got severe glitches in greeter, Firefox, Electron apps, and Gala. So clearly not an easy universal solution. But it does seem to confirm my suspicions that it is related to graphics drivers in some way.

**Comment by mnavarrocarter** [comment] 2018-10-24 13:03
I can confirm that @rkoesters suggestion also fixes the issue in my HD Graphics 520 (rev 07). No glitches detected. Tested in Chrome (YouTube), Postman (electron), Elementary Videos, VLC and everything works fine.

**Comment by mnavarrocarter** [comment] 2018-10-24 13:18
I was reading through the internet. Maybe the people that still have the screen flickering problem can try this config in `/etc/X11/xorg.conf.d/20-intel.conf`

```
Section "Device"
    Identifier "Intel Graphics"
    Driver "intel"
    Option "AccelMethod" "sna"
    Option "TearFree" "true"
    Option "DRI" "3"
EndSection
```

The source of this is [here](https://askubuntu.com/questions/752743/ubuntu-16-04-skylake-6th-generation-screen-flickering/756992). It's worth a read. There are some other configs that you may test with your hardware.

**Comment by rugglcon** [comment] 2018-10-24 20:05
Can confirm that the other config suggestion from @mnavarrocarter fixed the tearing and flickering at least

**Comment by peterrobertz** [comment] 2018-10-24 20:17
i can confirm @mnavarrocarter solution fixed the problem for me.

dell xps 9360r ; intel i8

before: fullscreen video mode = freeze; overall sluggish

after: its gone, feels much faster + fullscreen video is no problem anymore

@cassidyjames did you simply forget to ship this file /etc/X11/xorg.conf.d/20-intel.conf ?

thank you man!

**Comment by PNunesDev** [comment] 2018-10-24 21:29
@mnavarrocarter Unfortunaly I'm unable to find that file inside the X11 folder :/

**Comment by mnavarrocarter** [comment] 2018-10-24 21:37
@PNunesDev You can just create it :)

**Comment by PNunesDev** [comment] 2018-10-24 23:03
I've used the /usr/share/X11/xorg.conf.d folder and it worked immediatally.
As for the increased CPU load, it makes sense since GPU decoding probably gets disabled in videos and CPU needs to render it instead which is WAYYY less efficient.

Let's just hope this gets fixed quick.
If this gets fixed in the future, let me us know so we can roll back the changes and take advantage of the GPU decode ... again!
Thanks

**Comment by mnavarrocarter** [comment] 2018-10-25 01:36
AFAIK, X reads from both directories. The `usr` one is for the default config and the `etc` one is for custom. That's all I know I'm afraid. :stuck_out_tongue_closed_eyes: 

Cannot really comment in your second issue though. I don't have any benchmarks for that.

**Comment by yarbsemaj** [comment] 2018-10-25 20:14
Can confirm that @mnavarrocarter method works however playing a 1080p youtube video causes my cpu to almost top out

**Comment by jorge-aparicio** [comment] 2018-10-25 23:05
Using @mnavarrocarter works somewhat for me the high cpu usage still causes frame drops and stutters on my xps 13 using youtube on chrome

**Comment by jeanimator** [comment] 2018-11-01 00:51
I can confirm @mnavarrocarter  solution fixed the problem for me.

elementary OS 5.0 Juno (64-bit)
Built on Ubuntu 18.04 LTS
Linux 4.15.0-38-generic
GTK+ 3.22.30

Dual Core Intel® Core™ i5-5300U CPU @ 2.30GHz
Intel Corporation HD Graphics 5500 (rev 09)

**Comment by anarrestee** [comment] 2018-11-11 18:07
Does anyone know if we can expect a permanent fix from stable updates? Or would you advice to use the workarounds available, like the one suggested by @mnavarrocarter?

**Comment by belizeno** [comment] 2018-11-13 20:00
I can confirm this works on my computer.  There needs to be a permanent fix though.  Elementary Os is as perfect an OS as you can get, with this one tiny glitch messing things up on Intel Graphics HD Machines.

![screenshot from 2018-11-13 13-57-48](https://user-images.githubusercontent.com/13384547/48439600-4cfd4e80-e74c-11e8-9693-749f949fa944.png)

**Comment by anarrestee** [comment] 2018-11-14 13:03
After installing Firefox and VLC and testing the issue again, I can confirm (in my machine) it persists and seems confined to Videos app, even after using @mnavarrocarter solution.

**Comment by okitoxd** [comment] 2018-11-14 16:15
I have the same problem. I found that the video works fluid if i do use Picture in Picture feature over youtube video and the original video is in other working area.

**Comment by xayden** [comment] 2018-11-14 22:30
@mnavarrocarter solution worked fine for videos, but this issue is not with videos only, I have this issue while downloading on mega.nz or when loading a website the loading icon stops and doesn't show any content on the page unless I move the mouse, for mega.nz the download progress doesn't show any update unless I move the mose
![screenshot from 2018-11-15 00-28-45](https://user-images.githubusercontent.com/23618008/48516941-837eba80-e86d-11e8-9c30-16afd9157074.png)

**Comment by viniciusn** [comment] 2018-11-15 20:42
Same here, doesn't happen on Mozilla or Epiphany. Only Chrome, Chromiun or Opera, this is not an webkit engine glitch ?

**Comment by hunboy723** [comment] 2018-11-25 14:33
Kaffeine works on the first screen.

**Comment by xayden** [comment] 2018-11-26 20:11
Connecting external monitor with @mnavarrocarter solution doesn't solve the problem.

**Comment by Livotch** [comment] 2018-11-27 14:56
I had the same problem on Chrome, I disabled "Use hardware acceleration when available" in Chrome settings, it works fine now.

**Comment by BoredGitTechie** [comment] 2018-11-29 16:54
i have the same issue with freezing, did the same as Livotch did a while ago and fixed on steam but found out that it affects games aswell as chrome, cant play some games only using a controller as it freezes and starts moving again when i move the mouse, rendering my controller pointless. do we have any fixes for this or is the freezing a dead end?

**Comment by pushqrdx** [comment] 2018-12-02 18:52
Even happens with Elementary Video, Chrome, Firefox even download progress..

**Comment by michaelsboost** [comment] 2018-12-02 21:16
I can confirm this is happening to me to on the newest Juno (at time of posting).

![screenshot from 2018-12-02 15-15-35](https://user-images.githubusercontent.com/2473707/49345056-407e5e80-f645-11e8-81dd-6473e0164528.png)

**Comment by viniciusn** [comment] 2018-12-04 23:13
Hi @cassidyjames should i have to downgrade to Loki ?

**Comment by danrabbit** [comment] 2019-09-27 19:09
Closing because this appears to have been fixed in Ubuntu

**Closed by danrabbit** 2019-09-27 19:09 UTC
Labels: Bounty, Priority: High, Status: Confirmed
